server:
  port: 8008
  
spring:
  datasource:
    url: jdbc:mysql://sql.freedb.tech/freedb_farmacristo
    username: freedb_farmacristo_user
    password: WTNBas7!qN!ZKx$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
